
[general]
app_name = "V V V V"
debug = true

[api_url]

api_base_url = "http://127.0.0.1:8000/api"
auth_login = "/auth/login"
is_logged_in = "/auth/is_logged_in"

list_states = "/states"
add_state = "/state"
update_state = "/admin/update_state"
delete_state = "/admin/delete_state"

list_districts = "/admin/districts_list"
add_district = "/admin/add_district"
update_district = "/admin/update_district"
delete_district = "/admin/delete_district"

list_constituencies = "/admin/assemblyconstituency"
add_constituency = "/admin/add_constituency"
update_constituency = "/admin/update_constituency"
delete_constituency = "/admin/delete_constituency"


[theme]
primaryColor="#1b4332"
backgroundColor="#fff"
secondaryBackgroundColor="#e9ecef"
textColor="#000"
font="sans serif"


[client]

# Whether to enable st.cache.
# Default: true
caching = false


[logger]

toolbarMode = "developer"